### ISSUE TITLE
NPM 上没有 vue-number-directive 包

### ISSUE THREAD

**Issue by FlashWo1f** [awamwang/vue-number-directive#5]
Couldn't find package "vue-number-directive" on the "npm" registry.

**Comment by awamwang** [comment]
现在已经有了0.0.3-beta版本,链接如下。
[npm](https://www.npmjs.com/package/vue-number-directive/v/0.0.3)

发布并撤回了0.0.1版本，所以没0.0.1。
想写完测试再加其他功能，现在就只有对基本格式符号的控制，长度的控制，正负的控制。
